"""
AI-SUGGESTED IMPLEMENTATION
Generated by GitHub Copilot/Tabnine
"""

def sort_dicts_ai(data, key):
    """
    AI-suggested implementation using sorted and lambda
    """
    return sorted(data, key=lambda x: x[key])

# Test data
test_data = [
    {"name": "John", "age": 25},
    {"name": "Alice", "age": 30},
    {"name": "Bob", "age": 20}
]

# Test the AI implementation
result = sort_dicts_ai(test_data, "age")
print("AI sort result:", result)